<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMxF7Ss\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMxF7Ss/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMxF7Ss.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMxF7Ss\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNMxF7Ss\App_KernelDevDebugContainer([
    'container.build_hash' => 'NMxF7Ss',
    'container.build_id' => '315fba16',
    'container.build_time' => 1758279428,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMxF7Ss');
