<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUFnR8qa\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUFnR8qa/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerUFnR8qa.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerUFnR8qa\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerUFnR8qa\App_KernelDevContainer([
    'container.build_hash' => 'UFnR8qa',
    'container.build_id' => 'd77d6741',
    'container.build_time' => 1758277208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUFnR8qa');
