<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ANBCBRNService extends App_KernelDevContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.aNBCBRN' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['.messenger.handler_descriptor.aNBCBRN'])) {
            return $container->privates['.messenger.handler_descriptor.aNBCBRN'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['.messenger.handler_descriptor.aNBCBRN'])) {
            return $container->privates['.messenger.handler_descriptor.aNBCBRN'];
        }

        return $container->privates['.messenger.handler_descriptor.aNBCBRN'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\CheckScanStatusMessageHandler(($container->privates['App\\Service\\DebrickedClient'] ?? $container->load('getDebrickedClientService')), $a, $b, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))), []);
    }
}
