<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_LSOsRZPService extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored.LSOsRZP' shared service.
     *
     * @return \App\Repository\RepositoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RepositoryController::repositoryScans()": the $repositoryRepo argument is type-hinted with the non-existent class or interface: "App\\Repository\\RepositoryRepository".');
    }
}
