<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YiifflsService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.yiiffls' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yiiffls'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repositoryRepo' => ['privates', '.errored.LSOsRZP', NULL, 'Cannot determine controller argument for "App\\Controller\\RepositoryController::repositoryScans()": the $repositoryRepo argument is type-hinted with the non-existent class or interface: "App\\Repository\\RepositoryRepository".'],
            'scanRepo' => ['privates', 'App\\Repository\\ScanResultRepository', 'getScanResultRepositoryService', true],
        ], [
            'repositoryRepo' => '?',
            'scanRepo' => 'App\\Repository\\ScanResultRepository',
        ]);
    }
}
