<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_BI3xsXrService extends App_KernelDevContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.bI3xsXr' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['.messenger.handler_descriptor.bI3xsXr'])) {
            return $container->privates['.messenger.handler_descriptor.bI3xsXr'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['.messenger.handler_descriptor.bI3xsXr'])) {
            return $container->privates['.messenger.handler_descriptor.bI3xsXr'];
        }

        return $container->privates['.messenger.handler_descriptor.bI3xsXr'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\UploadFileMessageHandler($a, $b), []);
    }
}
