<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RB09lG7Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.RB09lG7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RB09lG7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repositoryRepo' => ['privates', '.errored.9UJYEKW', NULL, 'Cannot determine controller argument for "App\\Controller\\RepositoryController::listRepositories()": the $repositoryRepo argument is type-hinted with the non-existent class or interface: "App\\Repository\\RepositoryRepository".'],
        ], [
            'repositoryRepo' => '?',
        ]);
    }
}
