<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RepositoryController::listRepositories' => ['privates', '.service_locator.RB09lG7', 'get_ServiceLocator_RB09lG7Service', true],
            'App\\Controller\\RepositoryController::repositoryScans' => ['privates', '.service_locator.yiiffls', 'get_ServiceLocator_YiifflsService', true],
            'App\\Controller\\ScanController::scanDetails' => ['privates', '.service_locator.84HqLs9', 'get_ServiceLocator_84HqLs9Service', true],
            'App\\Controller\\UploadController::list' => ['privates', '.service_locator.pArDVJZ', 'get_ServiceLocator_PArDVJZService', true],
            'App\\Controller\\UploadController::status' => ['privates', '.service_locator.pArDVJZ', 'get_ServiceLocator_PArDVJZService', true],
            'App\\Controller\\UploadController::upload' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\RepositoryController:listRepositories' => ['privates', '.service_locator.RB09lG7', 'get_ServiceLocator_RB09lG7Service', true],
            'App\\Controller\\RepositoryController:repositoryScans' => ['privates', '.service_locator.yiiffls', 'get_ServiceLocator_YiifflsService', true],
            'App\\Controller\\ScanController:scanDetails' => ['privates', '.service_locator.84HqLs9', 'get_ServiceLocator_84HqLs9Service', true],
            'App\\Controller\\UploadController:list' => ['privates', '.service_locator.pArDVJZ', 'get_ServiceLocator_PArDVJZService', true],
            'App\\Controller\\UploadController:status' => ['privates', '.service_locator.pArDVJZ', 'get_ServiceLocator_PArDVJZService', true],
            'App\\Controller\\UploadController:upload' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\RepositoryController::listRepositories' => '?',
            'App\\Controller\\RepositoryController::repositoryScans' => '?',
            'App\\Controller\\ScanController::scanDetails' => '?',
            'App\\Controller\\UploadController::list' => '?',
            'App\\Controller\\UploadController::status' => '?',
            'App\\Controller\\UploadController::upload' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RepositoryController:listRepositories' => '?',
            'App\\Controller\\RepositoryController:repositoryScans' => '?',
            'App\\Controller\\ScanController:scanDetails' => '?',
            'App\\Controller\\UploadController:list' => '?',
            'App\\Controller\\UploadController:status' => '?',
            'App\\Controller\\UploadController:upload' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
