<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebrickedClientService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Service\DebrickedClient' shared autowired service.
     *
     * @return \App\Service\DebrickedClient
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\DebrickedClient'] = new \App\Service\DebrickedClient(($container->privates['http_client'] ?? $container->load('getHttpClientService')), $container->getEnv('DEBRICKED_API_BASE_URL'), $container->getEnv('DEBRICKED_API_TOKEN'), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
