<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebrickedTestCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Command\DebrickedTestCommand' shared autowired service.
     *
     * @return \App\Command\DebrickedTestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\DebrickedTestCommand'] = $instance = new \App\Command\DebrickedTestCommand(($container->privates['App\\Service\\DebrickedClient'] ?? $container->load('getDebrickedClientService')));

        $instance->setName('app:debricked:test');

        return $instance;
    }
}
