<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScanResultRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\ScanResultRepository' shared autowired service.
     *
     * @return \App\Repository\ScanResultRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ScanResultRepository'] = new \App\Repository\ScanResultRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
