<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScanControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\ScanController' shared autowired service.
     *
     * @return \App\Controller\ScanController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ScanController'] = $instance = new \App\Controller\ScanController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ScanController', $container));

        return $instance;
    }
}
