<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadedDependencyFileRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\UploadedDependencyFileRepository' shared autowired service.
     *
     * @return \App\Repository\UploadedDependencyFileRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UploadedDependencyFileRepository'] = new \App\Repository\UploadedDependencyFileRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
