<?php

namespace ContainerUFnR8qa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\UploadController' shared autowired service.
     *
     * @return \App\Controller\UploadController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));
        $b = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $container->services['App\\Controller\\UploadController'] = $instance = new \App\Controller\UploadController($a, new \App\Service\FileUploadService((\dirname(__DIR__, 3).'/uploads'), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), $a, $b), $b);

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\UploadController', $container));

        return $instance;
    }
}
